# 将一个NLP中的小知识
- 如何将一个string转换成一个vector来表示呢？
- 方法1：one-hot编码，即每个单词用一个独一无二的one-hot编码来表示，缺点：编码过于稀疏，切断了每个单词之间的联系，比如like,dislike。
- 方法2：embedding。很常用的方法，很好，很强大。

## pytorch中的数据类型的区别
比如float类型。torch.float和torch.cuda.float是不一样的，一个在cpu的内存上，而另一个在gpu上，一般来说，在用pytorch进行编程的时候很少显示的用torch.cuda.float，因为有to方法的存在，一切都变得容易了许多

In [17]:
import torch
import numpy as np

In [9]:
# type check
a = torch.randn(2, 3)
print(a.type())
print(a.dtype)
print(type(a))
print(isinstance(a, torch.FloatTensor))
# 我的电脑没有GPU啊啊啊。。不支持gpu加速运算
if torch.cuda.is_available():
    print(isinstance(a, torch.cuda.FloatTensor))
    a = a.cuda()
    print(isinstance(a, torch.cuda.FloatTensor))

torch.FloatTensor
torch.float32
<class 'torch.Tensor'>
True


In [12]:
# scalar，比如loss
a = torch.tensor(1.)
print(a)
print(a.dim())  # 注意dim()代表的是Rank，要和size()区分开来
print(a.size())
print(a.shape)

tensor(1.)
0
torch.Size([])
torch.Size([])


In [26]:
# vector，比如bias
a = torch.tensor([1.])
print(a)
print(a.dim(), a.size(), a.shape)
b = torch.FloatTensor(2) # 此时是一个随机初始化的vector
print(b)
c = np.ones([2])
c_tensor = torch.from_numpy(c)
print(c_tensor)
# 注意[1.]和1.0的区别，前者是长度为1的vector，后者是一个真正的scalar

tensor([1.])
1 torch.Size([1]) torch.Size([1])
tensor([-4.4716e-35,  3.0707e-41])
tensor([1., 1.], dtype=torch.float64)


In [29]:
# dim=2，带有batch的linear层的输入
a = torch.randn(2, 3)
print(a)
b = torch.FloatTensor(2, 3) # 随机初始化
print(b)
print(a.size(), a.size(0), a.size(1))
print(a.shape,a.shape[0], a.shape[1])

tensor([[-0.3335,  0.0702, -1.2592],
        [-1.7669, -0.8571, -0.2777]])
tensor([[-4.4325e-35,  3.0707e-41,  1.4013e-45],
        [ 0.0000e+00, -8.5711e-01, -2.7767e-01]])
torch.Size([2, 3]) 2 3
torch.Size([2, 3]) 2 3


In [31]:
# dim=3 RNN input batch
# 比如 [10, 20, 100]  20个句子，每个句子有10个单词，每个单词用length=100的vector来表示
a = torch.rand(1, 2, 3)
print(a)
b = torch.FloatTensor(1, 2, 3)
print(b)
print(a[0]) # a[0]和a很像，注意区别
print(list(a.shape))

tensor([[[0.5293, 0.5398, 0.2651],
         [0.1321, 0.5153, 0.0456]]])
tensor([[[-1.8866e-35,  3.0707e-41,  1.4013e-45],
         [ 0.0000e+00,  1.4013e-45,  0.0000e+00]]])
tensor([[0.5293, 0.5398, 0.2651],
        [0.1321, 0.5153, 0.0456]])
[1, 2, 3]


In [36]:
# dim=4 CNN input batch
a = torch.rand(2, 3, 28, 28)
print(a.dim())
print(a.shape)
print(a.numel()) # 2*3*28*28

4
torch.Size([2, 3, 28, 28])
4704
