In [2]:
import numpy as np 
import torch

In [2]:
# import from numpy 
a = np.array([2, 2.3])
a_tensor = torch.from_numpy(a)
print(a_tensor)
b = np.zeros([4, 4])
b_tensor = torch.from_numpy(b)
print(b_tensor)

tensor([2.0000, 2.3000], dtype=torch.float64)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


In [4]:
# import from list
# 注意两个生成Tensor的函数 torch.tensor这个接受现成数据，torch.Tensor这个接受的是维度
a = torch.tensor([1.1, 1.2]) # 这个现成数据可以是list，也可以是numpy.ndarray
b = torch.tensor(np.array([1.1, 1.2]))
c = torch.tensor([
    [1.1, 1.2],
    [1.3, 1.4]
])
print(c)

d = torch.Tensor(2, 3) # dim=2, shape=Size([2, 3])
e = torch.FloatTensor(2, 3) # 和torch.Tensor的功能是一致的，只不过是随机初始化
print(a.shape, d.shape)

tensor([[1.1000, 1.2000],
        [1.3000, 1.4000]])
torch.Size([2]) torch.Size([2, 3])


In [7]:
# uninitialized tensor 
# 可以发现里面的数值有非常大的，也有非常小的数值。
a = torch.empty(1)
print(a)
b = torch.IntTensor(2, 3)
print(b)

tensor([-2.5348e+30])
tensor([[-254120656,      21992,          0],
        [         0,          0,          0]], dtype=torch.int32)


In [8]:
# set default type
a = torch.tensor([1.2, 3])
print(a.type())

# 设置Tensor的默认数据类型
torch.set_default_tensor_type(torch.DoubleTensor) # 在reinforce learning中double类型用的很多
b = torch.randn(3, 4)
print(b.type())

torch.FloatTensor
torch.DoubleTensor


In [12]:
# rand/rand_like, randint
# 往后我的默认Tensor公式就是DoubleTensor了
a = torch.rand(3, 3)
print(a)
b = torch.rand_like(a)
print(b)
print(b.type())
c = torch.randint(1, 10, [3, 3]) # 区间左比右开，只能保证数值在[1, 10)之间，但并不是均匀的
print(c)
print(c.dtype) # 可以看到c默认是torch.Int的

tensor([[0.3552, 0.5348, 0.8811],
        [0.9098, 0.1812, 0.6422],
        [0.6531, 0.8402, 0.0574]])
tensor([[0.9284, 0.6082, 0.9855],
        [0.8432, 0.7115, 0.2998],
        [0.5742, 0.0223, 0.1801]])
torch.DoubleTensor
tensor([[6, 3, 6],
        [7, 3, 3],
        [1, 8, 8]])
torch.int64


In [15]:
# randn
a = torch.randn(3, 3) # mean=0, std=1的正太分布
print(a)
# 如果要改变均值和标准差呢？
b = torch.normal(mean=torch.full([10], 0), std=torch.arange(1, 0, -0.1)) # 先展平，再reshape
print(b)

tensor([[ 1.0925, -0.2295,  0.9539],
        [-0.4511, -0.0571,  0.0302],
        [ 0.9890, -0.7051,  1.6851]])
tensor([-0.4162, -0.9232, -0.6424, -0.8921,  0.0802,  0.3457, -0.7742, -0.0441,
         0.1592, -0.0729])


In [16]:
# full 给某一个tensor以固定值填充
a = torch.full([2, 3], 7) # 2行3列的Tensor，值全部为7
print(a.type()) # Double
print(a)
b = torch.full([], 7)  # 注意b和c的区别
print(b)
c = torch.full([1], 7)
print(c)

torch.DoubleTensor
tensor([[7., 7., 7.],
        [7., 7., 7.]])
tensor(7.)
tensor([7.])


In [17]:
# arange
# 就记住第一个数一定是闭区间，第二个数一定是开区间就完事了
a = torch.arange(1, 10)
print(a)
b = torch.arange(10, -1, -1) 
print(b)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])


In [18]:
# linspacelogspace
a = torch.linspace(0, 10, steps=3) # 左闭右闭区间，steps的值为把这个区间等间隔的分成几个数，这里是三个数
print(a)
b = torch.logspace(0, 10, steps=11)  # 这是先用torch.linspace得到[0, 1, 2, ...10]，然后作为以10为底的指数的系数就完事了
print(b)

tensor([ 0.,  5., 10.])
tensor([1.0000e+00, 1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05,
        1.0000e+06, 1.0000e+07, 1.0000e+08, 1.0000e+09, 1.0000e+10])


In [19]:
# ones/zeros/eye/ones(zeros)_like
a = torch.ones(3, 3)
print(a)
b = torch.zeros(3, 3)
print(b)
c = torch.eye(3, 3)
print(c)
d = torch.eye(3) # 注意eye矩阵的特殊之处，给一个值的时候代表一个方阵，而非向量。并且eye矩阵的维度只能为2！
print(d)
e = torch.ones_like(d)
print(e)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [23]:
# randperm
# 类似与numpy中的np.random.permutation
a = torch.randn(2, 3)
print(a)
shuffle_index = torch.randperm(2)  # 注意值为0和1的混排，不包含2
print(shuffle_index)
a = a[shuffle_index] # fancy indexes操作
print(a)

tensor([[-0.6128,  1.6668,  0.3117],
        [-0.1924, -0.7213,  1.8010]])
tensor([1, 0])
tensor([[-0.1924, -0.7213,  1.8010],
        [-0.6128,  1.6668,  0.3117]])
