In [1]:
import torch 
import numpy as np

In [5]:
# indexing
a = torch.rand(4, 3, 28, 28) # batch_size=4, channels=3, height=28, width=28
print(a.size())
b = a[0]
print(b.size()) # [3, 3, 28, 28]
c = a[0, 0, 2, 3] # 第一张图片，第一个通道，h=2,w=3上的像素点的值
print(c)  # scalar

torch.Size([4, 3, 28, 28])
torch.Size([3, 28, 28])
tensor(0.7924)


In [8]:
# select first/last N
print(a[:2].shape) # [2, 3, 28, 28]
print(a[:2, :1, ...].shape) # [2, 1, 28, 28]
print(a[:2, 1:, ...].shape) # [2, 2, 28, 28]

print(a[:2, -1:, ...].shape) # [2, 1, 28, 28] 注意a[:2, -1, ...]要比a[:2, -1:, ...]少一个维度哦，因为你已经真正的进入到了那一个维度，而不是切片驳斥维度了
print(a[:2, -1, ...].shape)

torch.Size([2, 3, 28, 28])
torch.Size([2, 1, 28, 28])
torch.Size([2, 2, 28, 28])
torch.Size([2, 1, 28, 28])
torch.Size([2, 28, 28])


In [9]:
# select by steps
print(a[:, :, 0:28:2, 0:28:2].size()) # [4, 3, 14, 14]
print(a[:, :, ::2, ::2].size()) # [4, 3, 14, 14]

torch.Size([4, 3, 14, 14])
torch.Size([4, 3, 14, 14])


In [22]:
# select by specific index
# 用到Tensor的成员函数：index_select(dim, Tensor)
# 第0个维度，即Rank=0，选取0和2通道，注意dtype必须是torch.long类型
# 不论你index怎么写，必不降维
print(a.index_select(0, torch.tensor([0, 2], dtype=torch.long)).shape) # [2, 3, 28, 28]
print(a.index_select(2, torch.arange(0, 28, 2, dtype=torch.long)).shape) # [4, 3, 14, 28]

torch.Size([2, 3, 28, 28])
torch.Size([4, 3, 14, 28])


In [24]:
# ... 可用来推测维度，方便代码的编写
print(a[..., 0:28:2].shape) # [4, 3, 28, 14] 
print(a[0:1, ..., 0:28:4].shape) # [1, 3, 28, 7]

torch.Size([4, 3, 28, 14])
torch.Size([1, 3, 28, 7])


In [27]:
# select by mask
a = torch.randn(3, 4)
print(a)
mask = a.ge(0.5) # tensor的成员函数ge，代表了 >= 功能，相应的还有le功能？
print(mask)
b = a.masked_select(mask)
print(b) # 注意此时b的Size是不定长的向量，只是把所有满足条件的scalar tensor塞进b里面而已
print(b.size())

tensor([[ 0.0760, -0.2827, -1.0732,  1.0988],
        [ 1.8330, -0.3747,  1.4158, -0.5896],
        [ 1.4469,  0.2393, -0.4917, -0.8170]])
tensor([[0, 0, 0, 1],
        [1, 0, 1, 0],
        [1, 0, 0, 0]], dtype=torch.uint8)
tensor([1.0988, 1.8330, 1.4158, 1.4469])
torch.Size([4])


In [30]:
# select by flatten index，用的比较少
# 先flatten，再索引，注意索引也必须是long类型的Tensor，和index_select是一样的
# 只不过take是torch的函数，而不是Tensor的成员函数了！
a = torch.arange(0, 8, dtype=torch.float)
print(a)
b = torch.take(a, torch.tensor([0, 2, 7], dtype=torch.long)) # 
print(b)

tensor([0., 1., 2., 3., 4., 5., 6., 7.])
tensor([0., 2., 7.])
