# Broadcasting的优点
- Unsqueeze + expand操作
- 不需要拷贝数据，节省内存～
- 注意：match fron last dim，也就是从最小维开始进行匹配

In [9]:
import torch 
import numpy as np 
torch.set_default_tensor_type(torch.DoubleTensor)

In [12]:
a = torch.zeros(2, 2, 3, 3)
print(a)
b1 = torch.tensor([3], dtype=torch.double)
b2 = torch.tensor(1)
c1 = a + b1 # [1] -> [1, 1, 1, 3] -> [2, 2, 3, 3]
c2 = a + b2 # 0 -> [1] -> [1, 1, 1, 1] -> [2, 2, 3, 3] 前提都是最后一个维度已经匹配了，才能正常运行broadcasting操作
print(c1)
print(c2)

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])
tensor([[[[3., 3., 3.],
          [3., 3., 3.],
          [3., 3., 3.]],

         [[3., 3., 3.],
          [3., 3., 3.],
          [3., 3., 3.]]],


        [[[3., 3., 3.],
          [3., 3., 3.],
          [3., 3., 3.]],

         [[3., 3., 3.],
          [3., 3., 3.],
          [3., 3., 3.]]]])
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
