In [1]:
import torch
import numpy as np

In [2]:
# element-wise operation
# torch.add/sub/mul/div
a = torch.randn(3, 4)
b = torch.randn(4)
print('+', torch.all(torch.eq(a + b, torch.add(a, b))))
print('-', torch.all(torch.eq(a - b, torch.sub(a, b))))
print('*', torch.all(torch.eq(a * b, torch.mul(a, b))))
print('/', torch.all(torch.eq(a / b, torch.div(a, b))))

+ tensor(1, dtype=torch.uint8)
- tensor(1, dtype=torch.uint8)
* tensor(1, dtype=torch.uint8)
/ tensor(1, dtype=torch.uint8)


In [14]:
# 矩阵乘法
# torch.mm只适合2d tensor
# torch.matmul和 @ 适用于包括2d在内的所有满足规则的矩阵乘法
# 但是三者对于二维Tensor来说是等价的
# b_expand = b.unsqueeze(0).expand(3, 4).t() # [4, 3]
b_expand = b.unsqueeze(0).expand_as(a).t()
print(torch.mm(a, b_expand))
print(torch.matmul(a, b_expand))
print(a @ b_expand)

tensor([[-2.6817, -2.6817, -2.6817],
        [ 0.5276,  0.5276,  0.5276],
        [ 3.4451,  3.4451,  3.4451]])
tensor([[-2.6817, -2.6817, -2.6817],
        [ 0.5276,  0.5276,  0.5276],
        [ 3.4451,  3.4451,  3.4451]])
tensor([[-2.6817, -2.6817, -2.6817],
        [ 0.5276,  0.5276,  0.5276],
        [ 3.4451,  3.4451,  3.4451]])


In [16]:
# example
a = torch.rand(4, 3, 28, 64)
b = torch.rand(4, 3, 64, 32)
try:
    c = torch.mm(a, b)
except Exception:
    print('Error, torch.mm onply support 2d Tensor operation.')
d = torch.matmul(a, b)
print(d.shape) # [4, 3, 28, 32] # 注意此时只在最后的两维进行矩阵乘法，前面的维度保持不变
e = torch.rand(3, 64, 32)
f = torch.matmul(a, e) # matmul支持自动broadcasting，e先->[1, 3, 64, 32] -> [4, 3, 64, 32]，所以output shape=[4,3, 28, 32]
print(f.size())

Error, torch.mm onply support 2d Tensor operation.
torch.Size([4, 3, 28, 32])
torch.Size([4, 3, 28, 32])


In [19]:
# power
a = torch.full([2, 2], 3)
print(a ** 2, a.pow(2)) # 2代表为平方，所以3就是立方。以此类推
print(a ** 0.5, a.sqrt())
print(torch.rsqrt(a)) # 平方根的倒数

tensor([[9., 9.],
        [9., 9.]]) tensor([[9., 9.],
        [9., 9.]])
tensor([[1.7321, 1.7321],
        [1.7321, 1.7321]]) tensor([[1.7321, 1.7321],
        [1.7321, 1.7321]])
tensor([[0.5774, 0.5774],
        [0.5774, 0.5774]])


In [20]:
# exp/log
a = torch.ones(3, 3)
print(torch.exp(a)) # element-wise: e^i for i in a
b = torch.log(a) # 默认是以e为底的，2为底:torch.log2，10为底:torch.log10
print(b)

tensor([[2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [21]:
# Approximation
a = torch.tensor(3.14)
print(a.dim())
print(a.floor(), a.ceil(), a.trunc(), a.frac(),a.round()) # 下取整，上取整，截断，小数部分，四舍五入

0
tensor(3.) tensor(4.) tensor(3.) tensor(0.1400) tensor(3.)


In [22]:
# clamp
# 该函数的意义类似np.clip，只不过在传入一个参数的时候默认是看成最小值的限制值
grad = torch.rand(2, 3) * 15
print(grad)
max_ = torch.max(grad)
min_ = torch.min(grad)
print('min: ', min_, 'max: ', max_)
grad_min = grad.clamp(10) # Tensor中小于10的全部拉成10
print(grad_min)
grad = grad.clamp(0, 10) # Tensor中小于0的全部拉成0，大于10的全部拉成10
print(grad)

# 小技巧
# 在梯度爆炸的时候，一般是权重(w)太大了，导致梯度爆炸，此时我们可以打印  权重的梯度的二阶范数！一般应该在10以内！
# 打印方法：print(w.grad.norm(2))  2代表的2阶范数

tensor([[11.7749, 11.1175,  5.3519],
        [ 8.3907,  8.9612,  4.0661]])
min:  tensor(4.0661) max:  tensor(11.7749)
tensor([[11.7749, 11.1175, 10.0000],
        [10.0000, 10.0000, 10.0000]])
tensor([[10.0000, 10.0000,  5.3519],
        [ 8.3907,  8.9612,  4.0661]])
